version: '3.3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es01
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./es01/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es02
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - es01
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - ./es02/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - esnet
  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    depends_on:
      - es01
      - es02
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    environment:
      SERVER_NAME: srvkibana
    #   ELASTICSEARCH_URL: http://es01:9200
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - es01
      - es02
    networks:
      - esnet

  filebeats:
    image: docker.elastic.co/beats/filebeat:6.2.4
    container_name: filebeats
    volumes:
      - ./filebeats/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeats/logs/:/tmp/logs/
    networks:
      - esnet
    depends_on:
      - es01
      - es02
      - logstash
      - kibana      
volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
networks:
  esnet: