filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

# processors:
# - add_cloud_metadata: ~

# output.elasticsearch:
#   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#   username: '${ELASTICSEARCH_USERNAME:}'
#   password: '${ELASTICSEARCH_PASSWORD:}'

###################### Filebeat Configuration Example 

filebeat.inputs:
- type: log
  enabled: true
  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    # - /var/log/*.log
    #- c:\programdata\elasticsearch\logs\*
    #- C:\elasticstack\filebeat-5.5.1-windows-x86_64\logs\*
    - /tmp/cisco.log
    #- /usr/share/app/place1/app.log.*

#----------------------------- Logstash output 
output.logstash:

  # The Logstash hosts

  hosts: ["logstash:5044"]